api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
#  formats:
#    json:
#      mime_types: ['application/json']
  eager_loading:
    enabled: true
#  collection:
#    order_parameter_name: '_order'
